
var x = 6.0; var y = 2; var z = 4.000; var a = 8; var b = 7.5; var c = 12; 
var qa = x - y > a;
var qb = x - y * a > c % y;
var qc = y != c;
var qd = x * y != c;
var qe = (c % y) <= (y & c);
var qf = a < b;
var qg = z / a + (x * y) - 5 >= b;
var qh = c * z + 2 == a * x + y;
var qi = c == z + b;
var qj = y * 2 != 7 - b;
console.log("a.", qa);
console.log("b.", qb);
console.log("c.", qc);
console.log("d.", qd);
console.log("e.", qe);
console.log("f.", qf);
console.log("g.", qg);
console.log("h.", qh);
console.log("i.", qi);
console.log("j.", qj);
